output_dir = "gs/test"

run_duration = 600
run_max_attempts = 8
backoff_initial_secs = 15
early_stop_dur = 60
early_stop_check_interval = 5
early_stop_fps_threshold = 114

[perfetto]
config_dir = "./perfetto_configs"
record_script = "./record_android_trace"

[sgame]
package_name = "com.tencent.tmgp.sgame"
package_name_short = "cent.tmgp.sgame"
resource_dir = "./resources/sgame"

