[project]
name = "grid-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "huoxj", email = "2567499168@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

